# Generated by Django 3.0.3 on 2020-05-03 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 3, 0, 13, 59, 879551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 0, 13, 59, 822585, tzinfo=utc), null=True),
        ),
    ]
